### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-labs#1]
- [ ] template arg to layout_from_callback (for DBC vs DDK vs custom)
- [ ] component_from_callback
- [ ] pattern arg to from_callback (for DCC vs DBC vs DDK)
- [ ] labels (kwarg and pack into id)
- [ ] uids
- [ ] error messages
